### ISSUE TITLE
Cannot import name 'safe_join' from 'flask' 

### ISSUE THREAD

**Issue by jsarver** [fpgmaas/simple-homepage#7]
Hi, I wanted to give this library a try so installed per your instructions and got the following error when running homepage init

```
from flask import Flask, abort, render_template, request, safe_join, send_from_directory
ImportError: cannot import name 'safe_join' from 'flask' 
```
I did some digging and it looks like flask deprecated safe_join in version 2.1. https://github.com/dmlc/GNNLens2/issues/14

**Comment by fpgmaas** [comment]
Strange. I am trying to reproduce your issue, but I fail to do so. I don't see `Flask` in `poetry.lock`, nor do I see it in my virtual environment locally. Could you give me a little bit more information about your environment? e.g. the python version and possible the installed versions of the project's dependencies?

**Comment by jsarver** [comment]
Well, this is embarrassing, apparently I installed another python lib call homepage, which also has a homepage init command. I have since uninstalled that lib and yours is working perfectly. Sorry for the confusion.

**Comment by fpgmaas** [comment]
Haha, no worries! Funny coincidence that that project also contains the `homepage init` command. Thanks for considering to improve this project by raising the issue anyways!
